const subjects = [
  {
    id: 1,
    mapel: "Matematika",
    title: "Aljabar Dasar",
    material: "Pengenalan variabel, persamaan linear, dan operasi dasar.",
    category: "Science",
    level: "Beginner",
    image: "https://via.placeholder.com/150?text=Matematika",
  },
  {
    id: 2,
    mapel: "Bahasa Inggris",
    title: "Grammar Dasar",
    material: "Belajar struktur kalimat dasar dan penggunaan kata kerja.",
    category: "Language",
    level: "Intermediate",
    image: "https://via.placeholder.com/150?text=Bahasa+Inggris",
  },
  {
    id: 3,
    mapel: "Fisika",
    title: "Hukum Newton",
    material: "Pembahasan tentang gerak dan gaya menggunakan hukum Newton.",
    category: "Science",
    level: "Advanced",
    image: "https://via.placeholder.com/150?text=Fisika",
  },
  {
    id: 4,
    mapel: "Sejarah",
    title: "Perang Dunia II",
    material: "Analisis peristiwa besar selama Perang Dunia II.",
    category: "History",
    level: "Intermediate",
    image: "https://via.placeholder.com/150?text=Sejarah",
  },
  {
    id: 5,
    mapel: "Kimia",
    title: "Ikatan Kimia",
    material: "Pengenalan jenis ikatan kimia dan reaksinya.",
    category: "Science",
    level: "Beginner",
    image: "https://via.placeholder.com/150?text=Kimia",
  },
  {
    id: 6,
    mapel: "Ekonomi",
    title: "Prinsip Dasar Ekonomi",
    material: "Dasar-dasar ekonomi mikro dan makro untuk pemula.",
    category: "Business",
    level: "Beginner",
    image: "https://via.placeholder.com/150?text=Ekonomi",
  },
  {
    id: 7,
    mapel: "Teknologi Informasi",
    title: "Dasar-Dasar Jaringan",
    material: "Memahami jaringan komputer dan cara kerjanya.",
    category: "Technology",
    level: "Intermediate",
    image: "https://via.placeholder.com/150?text=Teknologi+Informasi",
  },
  {
    id: 8,
    mapel: "Seni Rupa",
    title: "Menggambar Perspektif",
    material: "Teknik menggambar perspektif untuk seni visual.",
    category: "Art",
    level: "Beginner",
    image: "https://via.placeholder.com/150?text=Seni+Rupa",
  },
  {
    id: 9,
    mapel: "Biologi",
    title: "Ekosistem dan Lingkungan",
    material: "Mempelajari hubungan antara organisme dan lingkungan.",
    category: "Science",
    level: "Intermediate",
    image: "https://via.placeholder.com/150?text=Biologi",
  },
  {
    id: 10,
    mapel: "Olahraga",
    title: "Teknik Dasar Sepak Bola",
    material: "Pelajari teknik dasar bermain sepak bola.",
    category: "Physical Education",
    level: "Beginner",
    image: "https://via.placeholder.com/150?text=Olahraga",
  },
];

export default subjects;
